# Generated by Django 3.1.7 on 2021-05-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('bug', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('joinday', models.DateField()),
                ('image', models.FilePathField(path='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('customer_lang', models.CharField(max_length=3)),
                ('project_tech', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
